#!/usr/bin/env node
/* eslint-env node */
var program = require('commander');

program
  .version('0.0.1')
  .command('env', 'Run commands for the local environment')
  .command('deploy', 'Run deploy commands (requires authenticated and installed gcloud, kubectrl and helm cli tools)')
  .command('code', 'Run commands for the local codebase (unimplemented)')
;

program.parse(process.argv);

if (!program.args.length) {
  program.help();
}
